- name: play for variables
  hosts: all
  vars:
    URL: i hate you
  tasks:
    - name: print a value
      ansible.builtin.debug:
        msg: URL - {{URL}}
- name: play for variable files
  hosts: all
  vars_files:
    - sample-vars.yml
  tasks:
    - name: print URL
      ansible.builtin.debug:
        msg: URL - {{URL}}
- name: play for tasks level variation
  hosts: all
  tasks:
    - name: print URL1
      ansible.builtin.debug:
        msg: URL - {{URL}}
      vars:
        URL: APPLE
    - name: print URL2
      ansible.builtin.debug:
        msg: URL - {{URL}}
      vars:
        URL: SWEETY

