- name: play for variables
  hosts: all
  vars:
    URL: i hate you
  tasks:
    - name: print a value
      ansible.builtin.debug:
        msg: URL - {{URL}}
- name: play for variables files
  hosts: all
  vars_files:
    - sample.vars.yml
  tasks:
    - name: print URL
      ansible.builtin.debug:
        msg: URL - {{URL}}
