- name: play for variables
  hosts: all
  vars:
    URL: i hate you
  tasks:
    - name: print a value
      ansible.builtin.debug:
        msg: URL - {{URL}}
- name: play for variable files
  hosts: all
  vars_files:
    - sample-vars.yml
  tasks:
    - name: print URL
      ansible.builtin.debug:
        msg: URL - {{URL}}
- name: play for tasks level variation
  hosts: all
  tasks:
    - name: print URL1
      ansible.builtin.debug:
        msg: URL - {{URL}}
      vars:
        URL: APPLE
    - name: print URL2
      ansible.builtin.debug:
        msg: URL - {{URL}}
      vars:
        URL: SWEETY
## tasks for inventory variables
- name: play for inventory variables
  hosts: all
  tasks:
    - name: print URL1
      ansible.builtin.debug:
        msg: URL - {{URL}}
## command lines for variables
- name: play for inventory variables
  hosts: all
  tasks:
    - name: print URL1
      ansible.builtin.debug:
        msg: URL - {{URL}}
## variables from facts
- name: play for inventory variables
  hosts: all
  tasks:
    - name: print fact
      ansible.builtin.debug:
        msg: hostname - {{ansible_fqdn}}
## register a variables
- name: register variable
  hosts: all
  tasks:
    - name: uptime command
      ansible.builtin.shell: uptime
      register: out
    - name: print output
      ansible.builtin.debug:
        msg: {{out}}

